/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * PIM (Product Information Management) API
 * 商品情報管理システムのAPI定義
 * OpenAPI spec version: 1.0.0
 */

export interface Brand {
  /** ブランドID */
  brand_id?: string;
  /** ブランド名 */
  name?: string;
  /** ブランド名（英語） */
  name_en?: string;
  /** 説明 */
  description?: string;
  /** ロゴURL */
  logo_url?: string;
  /** ウェブサイトURL */
  website_url?: string;
  /** 有効フラグ */
  is_active?: boolean;
  created_at?: string;
  updated_at?: string;
}
