/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * PIM (Product Information Management) API
 * 商品情報管理システムのAPI定義
 * OpenAPI spec version: 1.0.0
 */
import type { ProductStatus } from './product_status';

export type GetProductsParams = {
page?: number;
/**
 * @maximum 100
 */
limit?: number;
category_id?: string;
brand_id?: string;
status?: ProductStatus;
/**
 * 商品名・説明での検索
 */
search?: string;
};
