/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * PIM (Product Information Management) API
 * 商品情報管理システムのAPI定義
 * OpenAPI spec version: 1.0.0
 */

/**
 * 画像タイプ
 */
export type ImageType = typeof ImageType[keyof typeof ImageType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ImageType = {
  main: 'main',
  sub: 'sub',
  detail: 'detail',
  package: 'package',
  manual: 'manual',
} as const;
