/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * PIM (Product Information Management) API
 * 商品情報管理システムのAPI定義
 * OpenAPI spec version: 1.0.0
 */
import type { ImageType } from './image_type';

export type PostProductsProductIdImagesBody = {
  file?: Blob;
  image_type?: ImageType;
  alt_text?: string;
  display_order?: number;
};
