/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * PIM (Product Information Management) API
 * 商品情報管理システムのAPI定義
 * OpenAPI spec version: 1.0.0
 */

/**
 * カスタムプロパティ
 */
export type ProductPhysicalPropertiesCustomProperties = { [key: string]: unknown };
