/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * PIM (Product Information Management) API
 * 商品情報管理システムのAPI定義
 * OpenAPI spec version: 1.0.0
 */
import type { ImageType } from './image_type';

export interface ProductImage {
  /** 画像ID */
  image_id?: string;
  /** 商品ID */
  product_id?: string;
  image_type?: ImageType;
  /** ファイル名 */
  file_name?: string;
  /** ファイルサイズ（bytes） */
  file_size?: number;
  /** MIMEタイプ */
  mime_type?: string;
  /** 画像URL */
  url?: string;
  /** 代替テキスト */
  alt_text?: string;
  /** 表示順序 */
  display_order?: number;
  /** メイン画像フラグ */
  is_primary?: boolean;
  created_at?: string;
  updated_at?: string;
}
