/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * PIM (Product Information Management) API
 * 商品情報管理システムのAPI定義
 * OpenAPI spec version: 1.0.0
 */
import type { Dimensions } from './dimensions';
import type { ProductPhysicalPropertiesWeight } from './product_physical_properties_weight';
import type { ProductPhysicalPropertiesVolume } from './product_physical_properties_volume';
import type { ProductPhysicalPropertiesCustomProperties } from './product_physical_properties_custom_properties';

export interface ProductPhysicalProperties {
  dimensions?: Dimensions;
  weight?: ProductPhysicalPropertiesWeight;
  volume?: ProductPhysicalPropertiesVolume;
  /** 色 */
  color?: string;
  /** 素材 */
  material?: string;
  /** 原産国 */
  origin_country?: string;
  /** 賞味期限（日数） */
  shelf_life?: number;
  /** 保存条件 */
  storage_conditions?: string;
  /** 取り扱い注意事項 */
  handling_precautions?: string;
  /** カスタムプロパティ */
  custom_properties?: ProductPhysicalPropertiesCustomProperties;
}
