/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * PIM (Product Information Management) API
 * 商品情報管理システムのAPI定義
 * OpenAPI spec version: 1.0.0
 */
import type { ProductBasicInfo } from './product_basic_info';
import type { ProductPhysicalProperties } from './product_physical_properties';
import type { ProductStatus } from './product_status';

export interface ProductUpdateRequest {
  product_code?: string;
  jan_code?: string;
  basic_info?: ProductBasicInfo;
  physical_properties?: ProductPhysicalProperties;
  status?: ProductStatus;
}
