/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * PIM (Product Information Management) API
 * 商品情報管理システムのAPI定義
 * OpenAPI spec version: 1.0.0
 */

/**
 * 商品ステータス
 */
export type ProductStatus = typeof ProductStatus[keyof typeof ProductStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductStatus = {
  draft: 'draft',
  active: 'active',
  inactive: 'inactive',
  discontinued: 'discontinued',
} as const;
