/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * PIM (Product Information Management) API
 * 商品情報管理システムのAPI定義
 * OpenAPI spec version: 1.0.0
 */
import type { ProductBasicInfo } from './product_basic_info';
import type { ProductPhysicalProperties } from './product_physical_properties';
import type { ProductImage } from './product_image';
import type { ProductStatus } from './product_status';

export interface Product {
  /** 商品ID */
  product_id?: string;
  /** 商品コード */
  product_code?: string;
  /** JANコード */
  jan_code?: string;
  basic_info?: ProductBasicInfo;
  physical_properties?: ProductPhysicalProperties;
  images?: ProductImage[];
  status?: ProductStatus;
  created_at?: string;
  updated_at?: string;
  created_by?: string;
  updated_by?: string;
}
