/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * PIM (Product Information Management) API
 * 商品情報管理システムのAPI定義
 * OpenAPI spec version: 1.0.0
 */

export interface ProductBasicInfo {
  /** 商品名 */
  name?: string;
  /** 商品名カナ */
  name_kana?: string;
  /** 商品説明 */
  description?: string;
  /** 短い説明 */
  short_description?: string;
  /** カテゴリID */
  category_id?: string;
  /** ブランドID */
  brand_id?: string;
  /** メーカー名 */
  manufacturer?: string;
  /** 型番 */
  model_number?: string;
  /** 価格 */
  price?: number;
  /** 通貨コード */
  currency?: string;
  /** 税率 */
  tax_rate?: number;
  /** 検索キーワード */
  keywords?: string[];
}
