/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * PIM (Product Information Management) API
 * 商品情報管理システムのAPI定義
 * OpenAPI spec version: 1.0.0
 */

/**
 * 単位タイプ
 */
export type UnitType = typeof UnitType[keyof typeof UnitType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UnitType = {
  length: 'length',
  weight: 'weight',
  volume: 'volume',
  area: 'area',
  temperature: 'temperature',
  time: 'time',
} as const;
