/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * PIM (Product Information Management) API
 * 商品情報管理システムのAPI定義
 * OpenAPI spec version: 1.0.0
 */
import type { UnitType } from './unit_type';

export interface Unit {
  /** 単位ID */
  unit_id?: string;
  /** 単位名 */
  name?: string;
  /** 単位記号 */
  symbol?: string;
  unit_type?: UnitType;
  /** 基準単位への変換係数 */
  conversion_factor?: number;
  /** 基準単位ID */
  base_unit_id?: string;
  /** 有効フラグ */
  is_active?: boolean;
  created_at?: string;
  updated_at?: string;
}
